import reducer from './reducers'
import middleware from './middleware'
import * as Cognito from './components'
import {
  COGNITO_CONFIGURE,
  COGNITO_REGISTER,
  COGNITO_REGISTERED,
  COGNITO_REGISTERING,
  COGNITO_REGISTER_SUCCESS,
  COGNITO_REGISTER_FAILURE,
  COGNITO_REFRESH_CREDENTIALS,
  COGNITO_LOGIN,
  COGNITO_LOGGING_IN,
  COGNITO_LOGIN_SUCCESS,
  COGNITO_LOGIN_FAILURE,
  COGNITO_SIGNOUT,
  COGNITO_SIGNOUT_FAILURE,
  COGNITO_SIGNOUT_SUCCESS,
  COGNITO_ERROR,
  cognitoConfigure,
  cognitoRegistering,
  cognitoRegisterSuccess,
  cognitoRegisterFailure,
  cognitoLoginSuccess,
  cognitoLoginFailure,
  cognitoLoggingIn,
  cognitoLogin,
  cognitoRegister,
  cognitoRefreshCredentials,
  cognitoSignout,
  cognitoSignOutSuccess,
  cognitoSignOutFailure,
  cognitoError,
} from './actions'

export {
  reducer,
  middleware,
  Cognito,
  COGNITO_CONFIGURE,
  COGNITO_REGISTER,
  COGNITO_REGISTERED,
  COGNITO_REGISTERING,
  COGNITO_REGISTER_SUCCESS,
  COGNITO_REGISTER_FAILURE,
  COGNITO_REFRESH_CREDENTIALS,
  COGNITO_LOGIN,
  COGNITO_LOGGING_IN,
  COGNITO_LOGIN_SUCCESS,
  COGNITO_LOGIN_FAILURE,
  COGNITO_SIGNOUT,
  COGNITO_SIGNOUT_FAILURE,
  COGNITO_SIGNOUT_SUCCESS,
  COGNITO_ERROR,
  cognitoConfigure,
  cognitoRegistering,
  cognitoRegisterSuccess,
  cognitoRegisterFailure,
  cognitoLoginSuccess,
  cognitoLoginFailure,
  cognitoLoggingIn,
  cognitoLogin,
  cognitoRegister,
  cognitoRefreshCredentials,
  cognitoSignout,
  cognitoSignOutSuccess,
  cognitoSignOutFailure,
  cognitoError,
}
